### ISSUE TITLE
Send message to a bot

### ISSUE THREAD

**Issue by felpsio** [xtin/TeleFred#1]
Thanks for the workflow. It's really useful.

I'm having problems to use it to send a message to a bot. Maybe your script isn't searching for bots when checking the contact list or it doesn't work well with names that starts with a `@` (the name of the bot I want to message is something like `@namebot`). Would you mind make this workflow works with bots as well?

I checked the `telegram-cli` and they can find bots normally using the command `contact_search`

**Comment by xtin** [comment]
for contact_search you seem to have to know the contact name exactly, partial matches result in {"result": "FAIL", "error_code": 100, "error": "RPC_CALL_FAIL 400: USERNAME_INVALID"}. 
However, in the updated version, if you've recently chatted with your bot, it shows up in "dialog_list", so in 0.0.4 it's accessible from the "t" command. This resolves this.
